# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardAuthor', models.CharField(default='Xavier Melville', max_length=50)),
                ('text', models.CharField(max_length=30)),
                ('adult', models.BooleanField(default=False)),
                ('cardType', models.CharField(default='Customer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NounCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardAuthor', models.CharField(default='Xavier Melville', max_length=50)),
                ('text', models.CharField(max_length=30)),
                ('adult', models.BooleanField(default=False)),
                ('cardType', models.CharField(default='Noun', max_length=50)),
            ],
        ),
    ]
